sonar.projectKey=ReTiCh-Corp_ReTiCh-User
sonar.organization=retich-corp

sonar.sources=.
sonar.exclusions=vendor/**

# Go détecte automatiquement les fichiers *_test.go comme fichiers de test
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Chemin vers le rapport de coverage généré par `go test -coverprofile`
sonar.go.coverage.reportPaths=coverage.out
